package com.musomi.manager.service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import com.musomi.manager.entity.Comment;
import com.musomi.manager.entity.SchoolSettings;
import com.musomi.manager.entity.Student;
import com.musomi.manager.entity.Term;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

/** Generates student report card PDFs. */
@Service
@RequiredArgsConstructor
@Slf4j
public class PdfService {

    /** PDF subject summary data. */
    public record SubjectAverage(String subjectName, BigDecimal average, String grade, int assessmentCount) {
    }

    /** Generates a one-page A4 report card PDF for a student and term. */
    public byte[] generateReportCard(Student student, Term term, SchoolSettings settings,
                                     List<SubjectAverage> subjects, BigDecimal overallAverage,
                                     String overallGrade, int position, int classSize, List<Comment> comments) {
        try (ByteArrayOutputStream output = new ByteArrayOutputStream()) {
            Document document = new Document(PageSize.A4);
            PdfWriter.getInstance(document, output);
            document.open();
            addReportContents(document, student, term, settings, subjects, overallAverage, overallGrade,
                    position, classSize, comments);
            document.close();
            log.info("Generated report card for student {} in term {}",
                    value(student == null ? null : student.getFullName(), "unknown"),
                    value(term == null ? null : term.getName(), "unknown"));
            return output.toByteArray();
        } catch (DocumentException | IOException exception) {
            throw new IllegalStateException("Unable to generate student report card PDF", exception);
        }
    }

    private void addReportContents(Document document, Student student, Term term, SchoolSettings settings,
                                   List<SubjectAverage> subjects, BigDecimal overallAverage,
                                   String overallGrade, int position, int classSize, List<Comment> comments)
            throws DocumentException {
        Font schoolFont = FontFactory.getFont(FontFactory.HELVETICA, 17, Font.BOLD);
        Font titleFont = FontFactory.getFont(FontFactory.HELVETICA, 14, Font.BOLD);
        String schoolName = settings == null || settings.getSchool() == null
                ? "Musomi Manager"
                : value(settings.getSchool().getName(), "Musomi Manager");
        document.add(new Paragraph(schoolName, schoolFont));
        if (settings != null && hasText(settings.getReportHeader())) {
            document.add(new Paragraph(settings.getReportHeader()));
        }
        document.add(new Paragraph(" "));
        String termName = value(term == null ? null : term.getName(), "Term");
        Integer academicYear = term == null || term.getAcademicYear() == null
                ? null
                : term.getAcademicYear().getYear();
        document.add(new Paragraph("Report Card — " + termName
                + (academicYear == null ? "" : " " + academicYear), titleFont));
        document.add(new Paragraph("Student: " + value(student == null ? null : student.getFullName(), "")));
        document.add(new Paragraph("Admission Number: "
                + value(student == null ? null : student.getAdmissionNumber(), "")));
        document.add(new Paragraph("Class: " + className(student)));
        document.add(new Paragraph("Stream: " + streamName(student)));
        document.add(new Paragraph(" "));
        addSubjectTable(document, subjects);

        document.add(new Paragraph("Overall Average: " + format(overallAverage)
                + "   Overall Grade: " + value(overallGrade, "N/A")
                + "   Position: " + position + "/" + classSize));
        addComments(document, comments);
        if (settings != null && hasText(settings.getReportFooter())) {
            document.add(new Paragraph(settings.getReportFooter()));
        }
        document.add(new Paragraph("Generated by Musomi Manager on " + LocalDate.now()));
    }

    private void addSubjectTable(Document document, List<SubjectAverage> subjects) throws DocumentException {
        PdfPTable table = new PdfPTable(4);
        table.setWidthPercentage(100);
        table.setWidths(new float[] {4, 2, 1, 2});
        addCell(table, "Subject");
        addCell(table, "Average");
        addCell(table, "Grade");
        addCell(table, "#Assessments");
        if (subjects != null) {
            for (SubjectAverage subject : subjects) {
                if (subject == null) {
                    continue;
                }
                addCell(table, value(subject.subjectName(), ""));
                addCell(table, format(subject.average()));
                addCell(table, value(subject.grade(), "N/A"));
                addCell(table, Integer.toString(subject.assessmentCount()));
            }
        }
        document.add(table);
        document.add(new Paragraph(" "));
    }

    private void addComments(Document document, List<Comment> comments) throws DocumentException {
        if (comments == null || comments.isEmpty()) {
            return;
        }
        document.add(new Paragraph("Comments"));
        for (Comment comment : comments) {
            if (comment == null) {
                continue;
            }
            String label = commentLabel(comment);
            document.add(new Paragraph("[" + label + "] " + value(comment.getCommentText(), "")));
        }
    }

    private String commentLabel(Comment comment) {
        String type = comment.getCommentType();
        if ("SUBJECT".equalsIgnoreCase(type)) {
            return comment.getSubject() == null ? "Subject" : value(comment.getSubject().getName(), "Subject");
        }
        if ("HEAD_TEACHER".equalsIgnoreCase(type)) {
            return "Head Teacher";
        }
        return "Class Teacher";
    }

    private String className(Student student) {
        return student == null || student.getCurrentClass() == null
                ? ""
                : value(student.getCurrentClass().getName(), "");
    }

    private String streamName(Student student) {
        return student == null || student.getCurrentStream() == null
                ? ""
                : value(student.getCurrentStream().getName(), "");
    }

    private void addCell(PdfPTable table, String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text));
        table.addCell(cell);
    }

    private String format(BigDecimal value) {
        return value == null ? "N/A" : value.setScale(1, java.math.RoundingMode.HALF_UP).toPlainString();
    }

    private String value(String value, String fallback) {
        return value == null || value.isBlank() ? fallback : value;
    }

    private boolean hasText(String value) {
        return value != null && !value.isBlank();
    }
}
